services:
  copypal-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "19234:19234"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-19234}
      - ARKIV_RPC_URL=${ARKIV_RPC_URL}
      - ARKIV_WS_URL=${ARKIV_WS_URL}
      - ARKIV_CHAIN_ID=${ARKIV_CHAIN_ID}
      - ARKIV_PRIVATE_KEY=${ARKIV_PRIVATE_KEY}
      - BASE_URL=${BASE_URL}
      - API_BASE_PATH=${API_BASE_PATH:-/api}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - FROM_EMAIL=${FROM_EMAIL}
      - FILESDB_ACCESS_TOKEN=${FILESDB_ACCESS_TOKEN}
      - GLITCHTIP_DSN=${GLITCHTIP_DSN}

  copypal-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.nginx
    ports:
      - "8881:80"
    env_file:
      - .env
    environment:
      - VITE_API_BASE=${VITE_API_BASE}
      - VITE_GLITCHTIP_DSN=${VITE_GLITCHTIP_DSN}
    depends_on:
      - copypal-backend
