services:
  copypal-backend:
    image: moonplkr/copypal-backend:latest
    ports:
      - "19234:19234"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-19234}
      - ARKIV_RPC_URL=${ARKIV_RPC_URL}
      - ARKIV_WS_URL=${ARKIV_WS_URL}
      - ARKIV_CHAIN_ID=${ARKIV_CHAIN_ID}
      - ARKIV_PRIVATE_KEY=${ARKIV_PRIVATE_KEY}
      - BASE_URL=${BASE_URL}
      - API_BASE_PATH=${API_BASE_PATH:-/api}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - FROM_EMAIL=${FROM_EMAIL}
      - FILESDB_ACCESS_TOKEN=${FILESDB_ACCESS_TOKEN}
      - GLITCHTIP_DSN=${GLITCHTIP_DSN}
    networks:
      - moon_golem_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.copypal-api.rule=Host(`copypal.online`) && PathPrefix(`/api/`)"
      - "traefik.http.routers.copypal-api.entrypoints=websecure"
      - "traefik.http.routers.copypal-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.copypal-api.priority=300"
      - "traefik.http.middlewares.copypal-api-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.copypal-api.middlewares=copypal-api-stripprefix"
      - "traefik.http.routers.copypal-api.service=copypal-api"
      - "traefik.http.services.copypal-api.loadbalancer.server.port=19234"
      - "traefik.http.services.copypal-api.loadbalancer.responseForwarding.flushInterval=1s"
      - "traefik.http.services.copypal-api.loadbalancer.passhostheader=true"
      # WebSocket support
      - "traefik.http.routers.copypal-ws.rule=Host(`copypal.online`) && Path(`/ws/progress`)"
      - "traefik.http.routers.copypal-ws.entrypoints=websecure"
      - "traefik.http.routers.copypal-ws.tls.certresolver=letsencrypt"
      - "traefik.http.routers.copypal-ws.priority=200"
      - "traefik.http.routers.copypal-ws.service=copypal-ws"
      - "traefik.http.services.copypal-ws.loadbalancer.server.port=19234"

  copypal-frontend:
    image: moonplkr/copypal-frontend:latest
    ports:
      - "8881:80"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - VITE_GLITCHTIP_DSN=${VITE_GLITCHTIP_DSN}
    depends_on:
      - copypal-backend
    networks:
      - moon_golem_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.copypal.rule=Host(`copypal.online`)"
      - "traefik.http.routers.copypal.entrypoints=websecure"
      - "traefik.http.routers.copypal.tls.certresolver=letsencrypt"
      - "traefik.http.routers.copypal.priority=50"
      - "traefik.http.services.copypal.loadbalancer.server.port=80"

networks:
  moon_golem_network:
    external: true